### ISSUE TITLE
gitlab-runner registration token deprecated

### ISSUE THREAD

**Issue by Normo** [hifis-net/ansible-role-gitlab-runner#104]
This feature was [deprecated](https://gitlab.com/gitlab-org/gitlab/-/issues/380872?_gl=1*1kraq3q*_ga*MTgzMDYxODQ2NC4xNjY1NzQ0Nzk3*_ga_ENFH3X7M5Y*MTY2OTE5NDk0NC4yNC4xLjE2NjkxOTU0MTAuMC4wLjA.) in GitLab 15.6 and is planned for removal in 16.0. This change is a breaking change. GitLab plans to introduce a new [GitLab Runner token architecture](https://docs.gitlab.com/ee/architecture/blueprints/runner_tokens/), which introduces a new method for registering runners and eliminates the legacy [runner registration token](https://docs.gitlab.com/ee/security/token_overview.html#runner-registration-tokens).

**Comment by tobiashuste** [comment]
The documentation now says that removal is scheduled for `17.0`.

> The ability to pass a runner registration token was [deprecated](https://gitlab.com/gitlab-org/gitlab/-/issues/380872) in GitLab 15.6 and is planned for removal in 17.0, along with support for certain configuration arguments. This change is a breaking change. GitLab plans to introduce a new [GitLab Runner token architecture](https://docs.gitlab.com/ee/architecture/blueprints/runner_tokens/), which introduces a new method for registering runners and eliminates the legacy [runner registration token](https://docs.gitlab.com/ee/security/token_overview.html#runner-registration-tokens).

https://docs.gitlab.com/runner/register/

As far as I can see there is no alternative command available for now.

**Comment by tobiashuste** [comment]
There might be an entire new option now on how to handle the configuration: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1932

**Comment by Normo** [comment]
Closed with #233
