### ISSUE TITLE
Errors on first run in check_mode

### ISSUE THREAD

**Issue by Normo** [hifis-net/ansible-role-gitlab-runner#159]
The role fails when applying in check_mode on a fresh target host:
```
TASK [hifis.gitlab_runner : Create SSH key pair for communicating with Runners.] ***
fatal: [gitlabcomhzdr]: FAILED! => {"changed": false, "msg": "The directory /etc/gitlab-runner does not exist or the file is not a directory", "name": "/etc/gitlab-runner"}
```

**Comment by tobiashuste** [comment]
The pipeline on the main branch revealed that we need to skip at least one other job. Currently, the `Identify which runners are registered` task is failing.

See https://github.com/hifis-net/ansible-role-gitlab-runner/actions/runs/5389295886/jobs/9783056744#step:5:359
